# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregistration',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
